--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonwynn10/MurderMysteryPMMP
branches:
- master
projects:
  MurderMysteryPMMP:
    path: ""
    libs:
    - src: Falkirks/spoondetector/spoondetector
      version: 3.0.0
...
