name: MurderMystery
author: AndersonWakeBR
version: 0.9
api: ["3.0.0"]
main: AndersonWakeBR\murder\Main
description: "Um Plugin de Minigame Murder Mystery para servidores PMMP"
load: POSTWORLD
website: "https://github.com/jasonwynn10/MurderMysteryPMMP"
commands:
  murdermystery:
    usage: "/mm [join|quit|info]"
    permission: murder.mystery.play
    description: "Adds the player to the Murder Mystery Game Queue"
    alias: ["mm","murder"]
permissions:
  murder.mystery.play:
    default: true
  murder.mystery.sign:
    default: op
    children:
      murder.mystery.sign.make:
        default: op
      murder.mystery.sign.remove:
        default: op
